server {
    listen 80;
    server_name manto.xin;

    access_log /www/sites/manto.xin/log/access.log main;
    error_log /www/sites/manto.xin/log/error.log;

    location ^~ /.well-known/acme-challenge/ {
        allow all;
        root /usr/share/nginx/html;
    }

    include /www/sites/manto.xin/proxy/*.conf;
}

